### ISSUE TITLE
how to visualise the Gaussian process?

### ISSUE THREAD

**Issue by ry-jojo** [joakimjohnander/DGPNet#3]
Hi there, I think your idea of using GP is very interesting. May I know how you visualize the Gaussian mean and covariance in the overview figure (Figure2 in the latest Arvix version)? Thanks in advance.

**Comment by joakimjohnander** [comment]
Hey ry-jojo,

We generated figure 2 with the following settings:
- Without GPO
- Without GP pyramid
- 1x1 local covariance window

The GP pyramid won't be in the way for the visualization, but to get the visualization of the mean and variance, do the following.
- Copy one of the runfiles (depending on if you desire 1-shot or 5-shot and pascal or coco)
- Use `AnnoEncoderAvgPool()` as `anno_encoder`
- Set `covar_size = 1`

Now look at line https://github.com/joakimjohnander/DGPNet/blob/main/fss/models/dgp.py#L478 , more specifically at the variable `predicted_segmentation_encodings[key]` . The keys will be "s32" and "s16", depending on which level in the pyramid we are at. The `predicted_segmentation_encodings[key]` will have the shape `(B, N, C, H, W)`, where B is the batch size, N is the number of query images (which should be 1), C the of the mean concatenated with the local covariance (with the settings above, it should be 1 for the mean and 1 for the covariance), H the image height, and W the image width. I think that you would like to visualize the
- mean as predicted_segmentation_encodings[key][b, 0, 0, :, :] ,
- variance as predicted_segmentation_encodings[key][b, 0, 1, :, :] .

Let me know if you run into any issues, it might be that I have misremembered some detail.

Best regards,
Joakim

**Comment by ry-jojo** [comment]
> Hey ry-jojo,
> 
> We generated figure 2 with the following settings:
> 
> * Without GPO
> * Without GP pyramid
> * 1x1 local covariance window
> 
> The GP pyramid won't be in the way for the visualization, but to get the visualization of the mean and variance, do the following.
> 
> * Copy one of the runfiles (depending on if you desire 1-shot or 5-shot and pascal or coco)
> * Use `AnnoEncoderAvgPool()` as `anno_encoder`
> * Set `covar_size = 1`
> 
> Now look at line https://github.com/joakimjohnander/DGPNet/blob/main/fss/models/dgp.py#L478 , more specifically at the variable `predicted_segmentation_encodings[key]` . The keys will be "s32" and "s16", depending on which level in the pyramid we are at. The `predicted_segmentation_encodings[key]` will have the shape `(B, N, C, H, W)`, where B is the batch size, N is the number of query images (which should be 1), C the of the mean concatenated with the local covariance (with the settings above, it should be 1 for the mean and 1 for the covariance), H the image height, and W the image width. I think that you would like to visualize the
> 
> * mean as predicted_segmentation_encodings[key][b, 0, 0, :, :] ,
> * variance as predicted_segmentation_encodings[key][b, 0, 1, :, :] .
> 
> Let me know if you run into any issues, it might be that I have misremembered some detail.
> 
> Best regards, Joakim

Hi Jokin, Many thanks for the reply. I followed the steps and got the visualization results :)

**Comment by joakimjohnander** [comment]
Glad to hear it. :)

**Comment by ry-jojo** [comment]
Thanks!
